### ISSUE TITLE
Cannot build the code

### ISSUE THREAD

**Issue by Anil-Gaihre** [sheldonucr/GLU_public#1]
Missing timer.h, symbolic.h while compiling

**Comment by psythefirst** [comment]
Can you please show the complete 'make' output, especially the error part? Those files are in `include/` and are included by makefile already

**Comment by Anil-Gaihre** [comment]
I made some modification in the Makefile as it was not detecting the cuda path. The missing file error is not coming now. However, I'm currently facing the error as below.

_"/sw/summit/cuda/10.1.243/bin/nvcc" -O3 -arch sm_35 -Xcompiler -Ipreprocess -I../include -Inicslu/include -c numeric.cu -o numeric.o
In file included from /usr/include/c++/4.8.2/unordered_set:35:0,
                 from ../include/symbolic.h:4,
                 from numeric.cu:4:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the **-std=c++11 or -std=gnu++11** compiler options.
 #error This file requires compiler and library support for the \
  ^
make: *** [numeric.o] Error 1_

The updated Makefile is below:-
# Makefile
DEBUG = 0

CUDA_PATH = /sw/summit/cuda/10.1.243/

LU_INC = -Ipreprocess -I../include -Inicslu/include
CUDA_INC = -I$(CUDA_PATH)/include

CUDA_LIB = -L$(CUDA_PATH)/lib64 -lcudart -lcuda -lcublas -lcusparse
PREPROCESS_LIBS = preprocess/preprocess.o nicslu/lib/nicslu.a nicslu/util/nicslu_util.a

NVCC = "$(shell which nvcc)"
CPP = "$(shell which g++)"
EXE = lu_cmd

CFLAGS = -O3 -m64 -Wall **-std=c++11** $(LU_INC) -DGLU_DEBUG=${DEBUG}
NVCCFLAGS = -O3 -arch sm_35 -Xcompiler $(LU_INC)

MAIN: $(EXE)

lu_cmd: Timer.o numeric.o symbolic.o lu_cmd.o $(PREPROCESS_LIBS)
	$(CPP) $(CFLAGS) $^ $(CUDA_LIB) -lrt -lpthread -o $@

Timer.o: Timer.cpp
	$(CPP) $(CFLAGS) -c $< -o $@

numeric.o: numeric.cu
	$(NVCC) $(NVCCFLAGS) -c $< -o $@

symbolic.o: symbolic.cc
	$(CPP) $(CFLAGS) -c $< -o $@

lu_cmd.o: lu_cmd.cpp
	$(CPP) $(CFLAGS) -c $< -o $@

preprocess/preprocess.o:
	make -C preprocess/

nicslu/lib/nicslu.a:
	make -C nicslu/

nicslu/lib/nicslu_util.a:
	make -C nicslu/

clean:
	rm -f *.o *~ *.so $(EXE)
	make -C preprocess/ clean
	make -C nicslu/ clean

distclean:
	rm -f *.o *~ *.so $(EXE)
	make -C nicslu/ clean
	make -C preprocess/ clean

**Comment by psythefirst** [comment]
I think adding `-std=c++11` to the line of `numeric.o` rules would do the work. Anyways, I made an update to this makefile and it should be cleaner now. Can you try again with that?

**Comment by Anil-Gaihre** [comment]
With the updated code I'm getting following error.

_make -C preprocess/
make[1]: Entering directory `/autofs/nccs-svm1_home1/anil/GLU_public/updated/code/GLU_public-master/src/preprocess'
gcc -c -g -O2 -Wall -Wextra -msse2 -DNO_ATOMIC -DSSE2  -I../nicslu/include -I../nicslu/util preprocess.c -o preprocess.o
gcc: error: unrecognized command line option '-msse2'
make[1]: *** [preprocess.o] Error 1
make[1]: Leaving directory `/autofs/nccs-svm1_home1/anil/GLU_public/updated/code/GLU_public-master/src/preprocess'
make: *** [preprocess/preprocess.o] Error 2_

The code can compile in other servers. With the compilation error relate to SSE2, do you think there is some issue when we try compiling in Power9 based system?

**Comment by psythefirst** [comment]
I have no experience with Power9 machines. I guess it does not support sse2 instructions and thus the problem. This part of code is related to nicslu, which is another lu solver from which glu uses some functions.
It should be fixable by disabling sse2. Just comment out the `-DSSE2` the 4th line of file `src/nicslu/make.inc`.

**Comment by Anil-Gaihre** [comment]
Can compile and run after commenting SSE flags at line 4 and 5 at the make.inc.

-Thank you!
