### ISSUE TITLE
Numerical accuracy of the algorithm

### ISSUE THREAD

**Issue by yfwang09** [sheldonucr/GLU_public#2]
Dear Sheldon,

I was trying to use your GLU3.0 code to calculate the signed log determinant log|A| of a large sparse matrix (~1M x 1M). I was testing your algorithm by using your example matrix add32.mtx. I modified the Symbolic_Matrix::solve function so that it returns the scaled diagonal terms of U:

```
vector<REAL> Symbolic_Matrix::solve(SNicsLU *nicslu, const vector<REAL> &rhs) {
    ...
    // diagonal of U
    for (unsigned jj = 0; jj < n; ++jj) {
        unsigned diag = l_col_ptr[jj];
        b[jj] = val[diag];
    }
    //apply col permutation and scaling
    if (mc64_scale)
        for (unsigned j = 0; j < n; ++j)
            x[j] = b[cp[j]] / cols[j];
    else
        for (unsigned j = 0; j < n; ++j)
            x[j] = b[cp[j]];
    return x;
}
```

I then output the log determinant value by using the following lines in the lu_cmd.cpp:

```
...
        vector<REAL> x = A_sym.solve(nicslu, b);
        double slogdet = 0;
        for (double xx: x) {
            x_f << setprecision(17) << xx << '\n';
            slogdet += log(abs(xx));
        }
        cout << "signed logdet(A) = " << setprecision(17) << slogdet << '\n';
...
```

The output is -22777.040843373397.

However, if I import the matrix file add32.mtx directly into MATLAB and perform LU decomposition:

```
rawdata = load('add32.mtx');
H = sparse(rawdata(2:end,1), rawdata(2:end,2), rawdata(2:end,3), rawdata(1,1),rawdata(1,2),rawdata(1,3));
[L, U, P, Q, D] = lu(H);
slogdet = full(sum(log(abs(diag(U)))) + sum(log(abs(diag(D)))));
```

The log determinant of the matrix is -22777.040875350347. The numerical error of your algorithm is actually ~1e-5 (relative error ~1e-9), which was a little bit higher than I expected considering the example only includes 4960 rows. I am afraid that the numerical error may accumulate if I apply your algorithm directly to my own matrix (1M x 1M). Do you have an idea where this error may come from and how could I avoid it?

Thanks,
Yifan

**Comment by psythefirst** [comment]
Hi, I tried this example with the distributed glu codes. I got slightly different output number (-22777.040837307977) but this still confirmed the problem.
I believe this problem comes from us using float instead of double by default. I got a result of -22777.0408753503 which matches your matlab output after switching to double. To use double, you can edit the type definitions in `include/type.h`. You might also need to add an option of `-arch sm_60` to `NVCCFLAGS` in `Makefile`, depending on your gpu generation.

**Comment by yfwang09** [comment]
Thank you for your suggestions! I am using NVIDIA TITAN Xp with CUDA 11.1, which -arch should I use?

**Comment by psythefirst** [comment]
I believe you can use sm_60.

**Comment by yfwang09** [comment]
Thank you. That works.

What is the time complexity of your algorithm? I was trying to calculate my matrix (1036800x1036800, nnz 757667034). The program has already been running for 10 hours, and still being stuck at the symbolic factorization step.

**Comment by psythefirst** [comment]
The symbolic step is about O(n*nnz) I would say.
I have tested one bigger example matrix (4623231x4623231), but with much fewer nnz (55280360). That finished in seconds.

**Comment by yfwang09** [comment]
Thank you for your reply. I actually have tried to use the program on my matrix, but after 10hrs of calculation, it failed at the symbolic step with the following error message:

```
Reading matrix...
Preprocessing matrix...
Preprocessing time: 50071.285836 ms
Matrix Row: 1036800
Original nonzero: 757667034
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
/var/spool/slurmd/job16024051/slurm_script: line 10: 63189 Aborted                 ./lu_cmd -i hessian_full.txt
```

Do you know where might be the problem coming from?

Thanks.

**Comment by psythefirst** [comment]
Probably a vector is becoming too large. Can you track the memory
consumption while running this case? If this indeed comes from large memory
consumption, we might need to refactor the symbolic part a bit.

**Comment by yfwang09** [comment]
How exactly can I track the memory consumption?

**Comment by psythefirst** [comment]
An easy way is to use a monitor software like top or htop. Just check how
much memory GLU consumes before it is killed, I would say like after 9
hours of running in your case.

**Comment by yfwang09** [comment]
Hi, I have tried to measure the resources used by the program. It turns out that the memory use of lu_cmd is only 12% of the memory (256GB in total), 7 mins before it is killed. The program ends with the same error message I showed above.

**Comment by psythefirst** [comment]
Thanks for helping observe the issue. I did some further research and found
a line of code that might be the source of the problem. However, I cannot
tell how the problem is formed without a real test case. Is it possible
that you can somehow share the matrix with us?

**Comment by psythefirst** [comment]
The problem should be coming from a vector::resize call. Probably the
argument of the call is incorrectly calculated and is unreasonably large,
hence the length_error.

**Comment by yfwang09** [comment]
Hi, Thank you for helping me narrowing down the problem! It would be great if you could test the code with my matrix. I have uploaded the file to [Dropbox](https://www.dropbox.com/s/94cqhp0bbn0tbji/matrix.tar.gz?dl=0). The unzipped file hessian_full.txt is ~25Gb, follows the same format as add32.mtx.

**Comment by psythefirst** [comment]
Hello. It seems the archive file is corrupted. I cannot extract the matrix
file either with 7zip on windows or tar on linux. Can you please re-upload?

**Comment by yfwang09** [comment]
Hello. Please try this [link](https://www.dropbox.com/s/cflodxkpqioaa4m/hessian_full.txt?dl=0), I have directly upload the .txt file to Dropbox.

**Comment by psythefirst** [comment]
Thank you. I am able to reproduce the issue now, will look into it.

**Comment by yfwang09** [comment]
Thank you for your help! Just an additional information about the matrix: The matrix is real symmetric matrix, with 1 negative eigen value (-0.19) and 3 zero eigen values, other eigen values ranges from ~2e-3 to 25. Therefore, the matrix is singular. I am not sure whether this will affect your algorithm, just FYI.

**Comment by psythefirst** [comment]
Hello. It turns out the nnz of your matrix is very large and causes an
overflow of unsigned int. GLU and the dependent nicslu both use unsigned
int for indexing. We might have a plan of fixing this. However, testing
your matrix also shows that the complexity symbolic phase is high, and
fixing this might be harder. We will let you know if we have further
updates with this issue.

**Comment by yfwang09** [comment]
Thank you. I was also testing your algorithm with sub-matrices of the full matrix. The symbolic step indeed takes very long:

| nrow | original nnz | symbolic nnz | symbolic time (s) |
| :---        |    :----:   |    :----:   |          ---: |
| 1101 | 136413 | 142443 | 0.01276 |
| 12423 | 6163525 | 21964309 | 22.8902 |
| 27876 | 15963838 | 117841514 | 288.859 |
| 49515 | 30294987 | 377783357 | 1805.89 |
| 77346 | 49152670 | 879311760 | 6658.56 |

It turns out that there is also a limit on the GPU memory, for the last case, there is an error message:

```
Reading matrix...
Preprocessing matrix...
Preprocessing time: 3704.704964 ms
Matrix Row: 77346
Original nonzero: 49152670
Symbolic nonzero: 879311760
Symbolic time: 6.65856e+06 ms
CSR time: 25270.4 ms
PredictLU time: 122761 ms
Number of levels: 41742
Leveling time: 882.764 ms
Device 0: TITAN Xp has been selected.
Total GPU time: 1.43493e-42 ms
**cudaErrorIllegalAddress
an illegal memory access was encountered**
signed logdet(A) = 179264.005218298
```

**Comment by psythefirst** [comment]
Yes, GLU assumes there being enough memory and tries to allocate all at
once. Each nonzero asks for at least 12B (a double for value and an
unsigned for indexing) so this is another problem.

**Comment by yfwang09** [comment]
Hi, In contrary to your reply below, I have tested a smaller matrix (49515x49515) with nnz (30294987). Your code still takes half an hour instead of seconds to finish the symbolic step. What issue do you think it is?

> 
> 
> The symbolic step is about O(n*nnz) I would say.
> I have tested one bigger example matrix (4623231x4623231), but with much fewer nnz (55280360). That finished in seconds.

**Comment by psythefirst** [comment]
This matrix is much denser than the matrices we tested. But I have no idea why that can be an issue at the moment.
